In [1]:
import pandas as pd
import numpy as np
import re
import random
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling as pp
import folium
import json
import pydeck as pdk
import geopandas as gpd

In [2]:
yp_df = pd.read_excel("../../data/moving_population/ingu_hour_yeungdeungpo.xlsx",sheet_name=0)

In [3]:
mp_df = pd.read_excel("../../data/moving_population/ingu_hour_mapo.xlsx",sheet_name=0)

In [4]:
ingu_var = [x for x in yp_df.columns if '_ingu' in x and len(x)>13]
print(len(ingu_var))
yp_df_2 = pd.melt(yp_df,['hour','latitude','longitude','gu_name','dong_name'],value_vars=ingu_var,var_name='성별연령대',value_name='인구')
yp_df_2.head()
yp_df_2['연령대'] = yp_df_2['성별연령대'].str.slice(stop=7)
yp_df_2['성별'] = yp_df_2['성별연령대'].str.slice(start=8)
yp_df_2 = yp_df_2.drop("성별연령대", axis=1)
yp_df_2['성별'] = yp_df_2.apply(lambda row:row['성별'].split('_')[0],axis=1)
yp_df_2.head()

18

   hour   latitude   longitude gu_name dong_name        인구      연령대    성별
0     0  37.510243  126.904651    영등포구     영등포본동  0.185763  under10  male
1     0  37.516164  126.917051    영등포구     영등포본동  0.112386  under10  male
2     0  37.512080  126.911425    영등포구     영등포본동  0.000000  under10  male
3     0  37.511581  126.901812    영등포구     영등포본동  0.417325  under10  male
4     0  37.514795  126.913667    영등포구     영등포본동  0.076697  under10  male

In [5]:
yp_df_2.groupby('dong_name')['latitude'].describe()

,count,mean,std,min,25%,50%,75%,max
dong_name,,,,,,,,
당산1동,128736.0,37.523915,0.002287,37.519236,37.521928,37.523744,37.525955,37.529119
당산2동,265320.0,37.533928,0.004710,37.526030,37.530034,37.533226,37.537741,37.544031
대림1동,86832.0,37.493676,0.002038,37.489070,37.492214,37.493588,37.495363,37.497191
대림2동,99360.0,37.489601,0.002182,37.485439,37.487713,37.489491,37.491287,37.494447
대림3동,160704.0,37.500029,0.003692,37.492621,37.497139,37.499851,37.502557,37.508383
도림동,101088.0,37.509134,0.001623,37.504353,37.507972,37.509314,37.510257,37.512071
문래동,310140.0,37.516519,0.002813,37.508830,37.514282,37.516532,37.518739,37.522736
신길1동,123552.0,37.512423,0.003080,37.505796,37.509868,37.512128,37.515268,37.518422
신길3동,91152.0,37.506210,0.001609,37.503009,37.504846,37.506173,37.507539,37.510271
신길4동,50544.0,37.507218,0.002066,37.503962,37.505334,37.507125,37.508933,37.511189
신길5동,84240.0,37.500903,0.001825,37.497171,37.499424,37.501218,37.502573,37.503954
신길6동,116208.0,37.499119,0.002382,37.493141,37.497658,37.499024,37.500810,37.503985
신길7동,108000.0,37.506223,0.003941,37.500365,37.503094,37.505369,37.508516,37.515309
양평1동,165024.0,37.525370,0.002425,37.520948,37.523240,37.525243,37.527284,37.530005
양평2동,401238.0,37.542188,0.006176,37.529561,37.537228,37.542633,37.547116,37.555643
여의동,1132074.0,37.527517,0.006884,37.515754,37.521702,37.527013,37.532832,37.544610
영등포동,235872.0,37.521567,0.003577,37.515194,37.518814,37.521071,37.523797,37.531883
영등포본동,145584.0,37.513681,0.001725,37.509781,37.512488,37.513457,37.514814,37.517062

In [6]:
mp_df_2 = pd.melt(mp_df,['hour','latitude','longitude','gu_name','dong_name'],value_vars=ingu_var,var_name='성별연령대',value_name='인구')
mp_df_2.head()
mp_df_2['연령대'] = mp_df_2['성별연령대'].str.slice(stop=7)
mp_df_2['성별'] = mp_df_2['성별연령대'].str.slice(start=8)
mp_df_2 = mp_df_2.drop("성별연령대", axis=1)
mp_df_2.head()
mp_df_2['성별'] = mp_df_2.apply(lambda row:row['성별'].split('_')[0],axis=1)
mp_df_2.head()

   hour   latitude   longitude gu_name dong_name        인구      연령대    성별
0     0  37.548776  126.951326     마포구       아현동  0.365343  under10  male
1     0  37.553301  126.955255     마포구       아현동  0.245545  under10  male
2     0  37.553755  126.955818     마포구       아현동  0.575684  under10  male
3     0  37.546512  126.949078     마포구       아현동  0.017785  under10  male
4     0  37.550584  126.952444     마포구       아현동  0.580266  under10  male

In [7]:
from branca.colormap import linear

colormap = linear.YlGn_09.scale(
    yp_df_2['인구'].min(),
    yp_df_2['인구'].max())
colormap

## 각 동별(row), 시간별(col), 성별(남/녀/전체) 인구 테이블

In [8]:
yp_groupby = yp_df_2[['hour','dong_name','성별','인구']].groupby(['hour','dong_name','성별'],as_index=False).sum()
mp_groupby = mp_df_2[['hour','dong_name','성별','인구']].groupby(['hour','dong_name','성별'],as_index=False).sum()

## 여의도, 마포구 데이터 이어주기 (concat)

In [9]:
ypmp_groupby = pd.concat([yp_groupby,mp_groupby])

### concat후 index reset (sorting을 안해주고 차이를 구하니 index가 달라 원하는 값을 얻지 못했다. 그래서 sorting 부분을 추가)

In [10]:
ypmp_groupby = ypmp_groupby.sort_values(by=['hour','dong_name','성별'])
ypmp_groupby['index'] = range(ypmp_groupby.shape[0])
ypmp_groupby = ypmp_groupby.set_index('index')
ypmp_groupby = ypmp_groupby.rename(columns={'dong_name':'dong'})
ypmp_groupby

       hour   dong      성별           인구
index
0         0    공덕동  female  8359.776753
1         0    공덕동    male  7549.914763
2         0   당산1동  female  4960.996613
3         0   당산1동    male  5268.878628
4         0   당산2동  female  6869.698127
...     ...    ...     ...          ...
1627     23  영등포본동    male  3949.204927
1628     23    용강동  female  4466.298791
1629     23    용강동    male  4513.142324
1630     23    합정동  female  4827.601396
1631     23    합정동    male  4912.320478

[1632 rows x 4 columns]

## 유동 인구 테이블로 변환

### 거주 인구 데이터 불러오기 --> skt 통신 데이터 수와 일치하지 않아 폐기

In [11]:
enrolled_ingu = pd.read_csv('서울시 주민등록인구 (동별) 통계.txt', sep="\t", header=2)
target_enrolled_ingu = enrolled_ingu[(enrolled_ingu['자치구']=='마포구') | (enrolled_ingu['자치구']=='영등포구')]
target_enrolled_ingu = target_enrolled_ingu[['행정동','계','남자','여자']]
target_enrolled_ingu.head()

     행정동        계       남자       여자
220   소계  385,925  181,303  204,622
221  용강동   22,441   10,655   11,786
222  대흥동   13,575    6,196    7,379
223  염리동   13,486    6,338    7,148
224  신수동   23,877   11,605   12,272

### 유동 인구 테이블로 변환 (새벽 3시 각 동별, 성별 인구와의 차를 유동인구로 정의)

In [12]:
move_ypmp_groupby = ypmp_groupby.copy()
for _hour in range(24):
    diff = np.array(move_ypmp_groupby[move_ypmp_groupby['hour']==_hour]['인구']) - np.array(move_ypmp_groupby[move_ypmp_groupby['hour']==3]['인구'])
    length = len(diff)
    move_ypmp_groupby.iloc[_hour*length:(_hour+1)*length,3] = diff
move_ypmp_groupby.to_csv('ypmp_hour_dong_sex_ingu.csv')

In [13]:
move_ypmp_groupby.iloc[3*length:(3+1)*length,:]

       hour   dong      성별   인구
index
204       3    공덕동  female  0.0
205       3    공덕동    male  0.0
206       3   당산1동  female  0.0
207       3   당산1동    male  0.0
208       3   당산2동  female  0.0
...     ...    ...     ...  ...
267       3  영등포본동    male  0.0
268       3    용강동  female  0.0
269       3    용강동    male  0.0
270       3    합정동  female  0.0
271       3    합정동    male  0.0

[68 rows x 4 columns]

### 각 동별(row), 시간별(col), 성별(남/녀/전체) 인구 테이블

In [14]:
move_ypmp_groupby[(move_ypmp_groupby['dong']=='공덕동')&(move_ypmp_groupby['hour']==0)]

       hour dong      성별          인구
index
0         0  공덕동  female   34.297368
1         0  공덕동    male  136.018577

In [15]:
total_move_groupby = move_ypmp_groupby.groupby(['hour','dong'],as_index=False,sort=False).sum()
total_move_groupby

     hour   dong            인구
0       0    공덕동    170.315945
1       0   당산1동    404.258111
2       0   당산2동    665.381161
3       0   대림1동    -51.322060
4       0   대림2동     65.283159
..    ...    ...           ...
811    23    염리동   4328.061172
812    23   영등포동  18566.384548
813    23  영등포본동   7624.564153
814    23    용강동   8979.441115
815    23    합정동   9739.921874

[816 rows x 3 columns]

### 각 동별(row), 시간별(col), 성별(남/녀/전체/남녀성비율) 인구 테이블

In [16]:
total_move_groupby['여성'] = np.array(move_ypmp_groupby[move_ypmp_groupby['성별']=='female']['인구'])
total_move_groupby['남성'] = np.array(move_ypmp_groupby[move_ypmp_groupby['성별']=='male']['인구'])
total_move_groupby['남성비율'] = np.abs(np.array(move_ypmp_groupby[move_ypmp_groupby['성별']=='male']['인구']))/(np.abs(np.array(move_ypmp_groupby[move_ypmp_groupby['성별']=='female']['인구']))+np.abs(np.array(move_ypmp_groupby[move_ypmp_groupby['성별']=='male']['인구'])))

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until

In [17]:
# total_move_groupby['dong'] = total_move_groupby['dong_name']
# del total_move_groupby['dong_name']
total_move_groupby

     hour   dong            인구           여성            남성      남성비율
0       0    공덕동    170.315945    34.297368    136.018577  0.798625
1       0   당산1동    404.258111   114.540847    289.717264  0.716664
2       0   당산2동    665.381161   203.303645    462.077516  0.694455
3       0   대림1동    -51.322060    -7.363765    -43.958295  0.856519
4       0   대림2동     65.283159    17.826607     47.456551  0.726934
..    ...    ...           ...          ...           ...       ...
811    23    염리동   4328.061172  2266.073173   2061.987999  0.476423
812    23   영등포동  18566.384548  8333.434325  10232.950223  0.551155
813    23  영등포본동   7624.564153  3675.359226   3949.204927  0.517958
814    23    용강동   8979.441115  4466.298791   4513.142324  0.502608
815    23    합정동   9739.921874  4827.601396   4912.320478  0.504349

[816 rows x 6 columns]

### 남성비율이 새벽 3시에 NAN으로 처리됨, 해당 비율은 원래 3시에 있던 인구들의 성비율로 대체

In [18]:
# total_move_groupby[total_move_groupby['hour']==3]
female = np.array(ypmp_groupby[(ypmp_groupby['hour']==3)&(ypmp_groupby['성별']=='female')]['인구'])
male = np.array(ypmp_groupby[(ypmp_groupby['hour']==3)&(ypmp_groupby['성별']=='male')]['인구'])
# ypmp_groupby[(ypmp_groupby['hour']==3)&(ypmp_groupby['성별']=='female')]
# ypmp_groupby[(ypmp_groupby['hour']==3)&(ypmp_groupby['성별']=='male')]
total_move_groupby.iloc[len(female)*3:len(female)*4,5] = male / (female + male)
total_move_groupby.iloc[len(female)*3:len(female)*4].head()

     hour  dong   인구   여성   남성      남성비율
102     3   공덕동  0.0  0.0  0.0  0.471041
103     3  당산1동  0.0  0.0  0.0  0.506753
104     3  당산2동  0.0  0.0  0.0  0.490787
105     3  대림1동  0.0  0.0  0.0  0.499187
106     3  대림2동  0.0  0.0  0.0  0.492161

In [19]:
total_move_groupby[total_move_groupby['남성비율'].isnull()]

Empty DataFrame
Columns: [hour, dong, 인구, 여성, 남성, 남성비율]
Index: []

In [20]:
total_move_groupby.head()

   hour  dong          인구          여성          남성      남성비율
0     0   공덕동  170.315945   34.297368  136.018577  0.798625
1     0  당산1동  404.258111  114.540847  289.717264  0.716664
2     0  당산2동  665.381161  203.303645  462.077516  0.694455
3     0  대림1동  -51.322060   -7.363765  -43.958295  0.856519
4     0  대림2동   65.283159   17.826607   47.456551  0.726934

## 각 동별(row), 특정 시간의 남/녀/전체(col) 인구 테이블

## 각 동별(row), 특정 시간대의 남/녀/전체(col) 인구 테이블

In [21]:
geo_path = 'geodata/seoul_yp_mp_map.geojson'
geo_str = json.load(open(geo_path, encoding='utf-8'))
# geo_str

In [22]:
df = gpd.read_file(geo_path)

In [23]:
def multipolygon_to_coordinates(x):
    lon, lat = x[0].exterior.xy
    return [[x, y] for x, y in zip(lon, lat)]

df['coordinates'] = df['geometry'].apply(multipolygon_to_coordinates)
del df['geometry']

In [24]:
select_geometry = df[['dong','coordinates']]
select_geometry.head()

  dong                                        coordinates
0  용강동  [[126.9445281888074, 37.54514799989514], [126....
1  대흥동  [[126.94681220459611, 37.5568494513366], [126....
2  염리동  [[126.94968160411595, 37.54381892668303], [126...
3  신수동  [[126.94073140875314, 37.546613890545075], [12...
4  서교동  [[126.91353477929526, 37.54948323708437], [126...

In [25]:
merged_move_ingu = pd.merge(total_move_groupby,select_geometry,on='dong')
# merged_move_ingu[(merged_move_ingu['dong']=='공덕동')]

## 가시화를 위해 인구 정규화

In [26]:
merged_move_ingu['정규화인구'] = merged_move_ingu['인구'] / merged_move_ingu['인구'].max()
merged_move_ingu
samlple_test_ingu = merged_move_ingu[(merged_move_ingu['hour']<7)]
samlple_test_ingu['시간별정규화인구'] = samlple_test_ingu['인구'] / samlple_test_ingu['인구'].max()
samlple_test_ingu.head()

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구,시간별정규화인구
0,0,공덕동,170.315945,34.297368,136.018577,0.798625,"[[126.96238687439413, 37.551503993982486], [12...",0.002297,0.006517
1,1,공덕동,68.601832,-6.065312,74.667144,0.924871,"[[126.96238687439413, 37.551503993982486], [12...",0.000925,0.002625
2,2,공덕동,96.101433,28.955433,67.146000,0.698699,"[[126.96238687439413, 37.551503993982486], [12...",0.001296,0.003677
3,3,공덕동,0.000000,0.000000,0.000000,0.471041,"[[126.96238687439413, 37.551503993982486], [12...",0.000000,0.000000
4,4,공덕동,15660.061730,8239.171461,7420.890268,0.473874,"[[126.96238687439413, 37.551503993982486], [12...",0.211214,0.599211

In [27]:
samlple_test_ingu2 = merged_move_ingu[(merged_move_ingu['hour']>=7)&(merged_move_ingu['hour']<11)]
samlple_test_ingu2['시간별정규화인구'] = samlple_test_ingu2['인구'] / samlple_test_ingu2['인구'].max()
samlple_test_ingu2.head()

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구,시간별정규화인구
7,7,공덕동,15130.336707,7904.714363,7225.622343,0.477559,"[[126.96238687439413, 37.551503993982486], [12...",0.204069,0.204069
8,8,공덕동,14857.823897,7890.408341,6967.415555,0.468939,"[[126.96238687439413, 37.551503993982486], [12...",0.200394,0.200394
9,9,공덕동,14669.436699,7768.340972,6901.095727,0.470440,"[[126.96238687439413, 37.551503993982486], [12...",0.197853,0.197853
10,10,공덕동,14453.705606,7706.655926,6747.049681,0.466804,"[[126.96238687439413, 37.551503993982486], [12...",0.194943,0.194943
31,7,당산1동,11553.069565,5668.851560,5884.218005,0.509321,"[[126.90283572959682, 37.52612206788627], [126...",0.155821,0.155821

In [28]:
samlple_test_ingu3 = merged_move_ingu[(merged_move_ingu['hour']>=11)&(merged_move_ingu['hour']<17)]
samlple_test_ingu3['시간별정규화인구'] = samlple_test_ingu3['인구'] / samlple_test_ingu3['인구'].max()
samlple_test_ingu3.head()

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구,시간별정규화인구
11,11,공덕동,14585.685457,7733.580539,6852.104918,0.469783,"[[126.96238687439413, 37.551503993982486], [12...",0.196723,0.197062
12,12,공덕동,14460.573140,7662.709733,6797.863406,0.470096,"[[126.96238687439413, 37.551503993982486], [12...",0.195036,0.195372
13,13,공덕동,14257.774788,7585.232723,6672.542066,0.467993,"[[126.96238687439413, 37.551503993982486], [12...",0.192300,0.192632
14,14,공덕동,14087.225632,7469.283939,6617.941693,0.469783,"[[126.96238687439413, 37.551503993982486], [12...",0.190000,0.190327
15,15,공덕동,14089.962750,7420.615256,6669.347494,0.473340,"[[126.96238687439413, 37.551503993982486], [12...",0.190037,0.190364

In [29]:
samlple_test_ingu4 = merged_move_ingu[(merged_move_ingu['hour']>=17)&(merged_move_ingu['hour']<20)]
samlple_test_ingu4['시간별정규화인구'] = samlple_test_ingu4['인구'] / samlple_test_ingu4['인구'].max()
samlple_test_ingu4.head()

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구,시간별정규화인구
17,17,공덕동,14543.037579,7508.701141,7034.336437,0.483691,"[[126.96238687439413, 37.551503993982486], [12...",0.196148,0.278280
18,18,공덕동,14477.569915,7364.923910,7112.646005,0.491287,"[[126.96238687439413, 37.551503993982486], [12...",0.195265,0.277027
19,19,공덕동,14430.436719,7331.474534,7098.962184,0.491944,"[[126.96238687439413, 37.551503993982486], [12...",0.194629,0.276126
41,17,당산1동,13430.404590,6529.918304,6900.486285,0.513796,"[[126.90283572959682, 37.52612206788627], [126...",0.181141,0.256990
42,18,당산1동,12055.610720,5602.020949,6453.589771,0.535318,"[[126.90283572959682, 37.52612206788627], [126...",0.162599,0.230683

In [30]:
samlple_test_ingu5 = merged_move_ingu[(merged_move_ingu['hour']>=20)&(merged_move_ingu['hour']<24)]
samlple_test_ingu5['시간별정규화인구'] = samlple_test_ingu5['인구'] / samlple_test_ingu5['인구'].max()
samlple_test_ingu5.head()

c:\project\venv\dacon\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구,시간별정규화인구
20,20,공덕동,14512.071719,7380.623322,7131.448398,0.491415,"[[126.96238687439413, 37.551503993982486], [12...",0.195730,0.292435
21,21,공덕동,14575.892497,7428.246684,7147.645814,0.490374,"[[126.96238687439413, 37.551503993982486], [12...",0.196591,0.293721
22,22,공덕동,14606.126609,7501.055986,7105.070623,0.486445,"[[126.96238687439413, 37.551503993982486], [12...",0.196999,0.294331
23,23,공덕동,14787.487700,7645.412500,7142.075200,0.482981,"[[126.96238687439413, 37.551503993982486], [12...",0.199445,0.297985
44,20,당산1동,10704.253914,5070.864248,5633.389666,0.526276,"[[126.90283572959682, 37.52612206788627], [126...",0.144373,0.215703

In [35]:
merged_move_ingu[merged_move_ingu['hour']==0]

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구
0,0,공덕동,170.315945,34.297368,136.018577,0.798625,"[[126.96238687439413, 37.551503993982486], [12...",0.002297
24,0,당산1동,404.258111,114.540847,289.717264,0.716664,"[[126.90283572959682, 37.52612206788627], [126...",0.005452
48,0,당산2동,665.381161,203.303645,462.077516,0.694455,"[[126.90771292525608, 37.54166765894863], [126...",0.008974
72,0,대림1동,-51.322060,-7.363765,-43.958295,0.856519,"[[126.90945108485955, 37.49258677822098], [126...",-0.000692
96,0,대림2동,65.283159,17.826607,47.456551,0.726934,"[[126.90633045911946, 37.488926320200605], [12...",0.000881
120,0,대림3동,150.597540,43.761355,106.836185,0.709415,"[[126.89821902246794, 37.50533375222877], [126...",0.002031
144,0,대흥동,64.841585,11.518665,53.322921,0.822357,"[[126.94681220459611, 37.5568494513366], [126....",0.000875
168,0,도림동,-12.517122,2.839968,-15.357090,0.843933,"[[126.91029490131251, 37.51070588023117], [126...",-0.000169
192,0,도화동,354.089502,103.350687,250.738815,0.708123,"[[126.95640090853102, 37.540584973834626], [12...",0.004776
216,0,망원1동,158.447700,33.704531,124.743168,0.787283,"[[126.90879758955973, 37.55741869164588], [126...",0.002137
240,0,망원2동,55.857061,12.499734,43.357327,0.776219,"[[126.90430487040659, 37.56239755941199], [126...",0.000753
264,0,문래동,121.662073,27.705201,93.956872,0.772277,"[[126.8922546215421, 37.52073773343492], [126....",0.001641
288,0,상암동,671.306340,290.799098,380.507242,0.566816,"[[126.89820025297284, 37.578261684023914], [12...",0.009054
312,0,서강동,255.592023,96.781114,158.810909,0.621345,"[[126.93407931603565, 37.553424478912795], [12...",0.003447
336,0,서교동,3099.646556,1101.679581,1997.966975,0.644579,"[[126.91353477929526, 37.54948323708437], [126...",0.041806
360,0,성산1동,-6.675466,-0.003101,-6.672365,0.999535,"[[126.91760207824414, 37.558838154880334], [12...",-0.000090
384,0,성산2동,73.074057,61.869989,11.204069,0.153325,"[[126.91180511327514, 37.57027898846455], [126...",0.000986
408,0,신길1동,74.895458,50.108397,24.787061,0.330955,"[[126.92601116467537, 37.51609788418517], [126...",0.001010
432,0,신길3동,-6.453585,18.519097,-24.972682,0.574193,"[[126.91016015543603, 37.50383464174522], [126...",-0.000087
456,0,신길4동,-0.443783,10.805709,-11.249492,0.510061,"[[126.91612345378918, 37.505646713217516], [12...",-0.000006
480,0,신길5동,14.671275,6.923266,7.748009,0.528107,"[[126.91016015543603, 37.50383464174522], [126...",0.000198
504,0,신길6동,96.891412,45.285738,51.605674,0.532613,"[[126.91545440395811, 37.504193340705775], [12...",0.001307
528,0,신길7동,56.196152,48.178069,8.018082,0.142680,"[[126.92082676829817, 37.501398550074335], [12...",0.000758
552,0,신수동,-7.901594,27.084659,-34.986253,0.563650,"[[126.94073140875314, 37.546613890545075], [12...",-0.000107
576,0,아현동,103.695280,17.474269,86.221011,0.831484,"[[126.95870842292932, 37.55665982191486], [126...",0.001399
600,0,양평1동,31.617933,3.753834,27.864099,0.881275,"[[126.89004358159242, 37.53037971846126], [126...",0.000426
624,0,양평2동,317.881842,76.187825,241.694017,0.760327,"[[126.89675635222676, 37.54631737308835], [126...",0.004287
648,0,여의동,1930.018625,611.855554,1318.163071,0.682979,"[[126.91451019650998, 37.540155932725305], [12...",0.026031
672,0,연남동,150.219282,51.316166,98.903117,0.658392,"[[126.92719890816318, 37.56182912348396], [126...",0.002026
696,0,염리동,-31.010987,-4.043474,-26.967513,0.869612,"[[126.94968160411595, 37.54381892668303], [126...",-0.000418
720,0,영등포동,955.093778,296.551255,658.542523,0.689506,"[[126.91320073649011, 37.524416576069264], [12...",0.012882
744,0,영등포본동,140.152204,65.624526,74.527679,0.531762,"[[126.9137350982683, 37.51138329319419], [126....",0.001890
768,0,용강동,292.656846,123.587092,169.069755,0.577706,"[[126.9445281888074, 37.54514799989514], [126....",0.003947
792,0,합정동,429.234524,104.445475,324.789050,0.756670,"[[126.91353477929526, 37.54948323708437], [126...",0.005789

In [75]:
merged_move_ingu

,hour,dong,인구,여성,남성,남성비율,coordinates,정규화인구
0,0,공덕동,170.315945,34.297368,136.018577,0.798625,"[[126.96238687439413, 37.551503993982486], [12...",0.002297
1,1,공덕동,68.601832,-6.065312,74.667144,0.924871,"[[126.96238687439413, 37.551503993982486], [12...",0.000925
2,2,공덕동,96.101433,28.955433,67.146000,0.698699,"[[126.96238687439413, 37.551503993982486], [12...",0.001296
3,3,공덕동,0.000000,0.000000,0.000000,0.471041,"[[126.96238687439413, 37.551503993982486], [12...",0.000000
4,4,공덕동,15660.061730,8239.171461,7420.890268,0.473874,"[[126.96238687439413, 37.551503993982486], [12...",0.211214
...,...,...,...,...,...,...,...,...
811,19,합정동,11730.859870,5954.384096,5776.475774,0.492417,"[[126.91353477929526, 37.54948323708437], [126...",0.158219
812,20,합정동,11493.901346,5835.635424,5658.265922,0.492284,"[[126.91353477929526, 37.54948323708437], [126...",0.155023
813,21,합정동,11000.648148,5571.030733,5429.617414,0.493573,"[[126.91353477929526, 37.54948323708437], [126...",0.148370
814,22,합정동,10419.194993,5177.774937,5241.420055,0.503054,"[[126.91353477929526, 37.54948323708437], [126...",0.140528
815,23,합정동,9739.921874,4827.601396,4912.320478,0.504349,"[[126.91353477929526, 37.54948323708437], [126...",0.131366

In [95]:
# Make layer 
layer = pdk.Layer( 'PolygonLayer', # 사용할 Layer 타입
                  merged_move_ingu, # 시각화에 쓰일 데이터프레임
                  get_polygon='coordinates', # geometry 정보를 담고있는 컬럼 이름
                  get_fill_color='[0, 255*정규화인구, 0]', # 각 데이터 별 rgb 또는 rgba 값 (0~255)
                  pickable=True, # 지도와 interactive 한 동작 on 
                  auto_highlight=True, # 마우스 오버(hover) 시 박스 출력 
                  getElevation='인구',
                  elevation_scale=0.1,
#                   elevation_range=[merged_move_ingu['인구'].min(), merged_move_ingu['인구'].max()],
                  extruded=True
                 ) 

# geojson = pydeck.Layer(
#     'GeoJsonLayer',
#     merged_move_ingu,
#     opacity=0.8,
#     stroked=False,
#     filled=True,
#     extruded=True,
#     wireframe=True,
#     get_elevation='properties.valuePerSqm / 20',
#     get_fill_color='[255, 255, properties.growth * 255]',
#     get_line_color=[255, 255, 255],
#     pickable=True
# )
# Set the viewport location 
center = [126.986, 37.565] 
view_state = pdk.ViewState( longitude=center[0], latitude=center[1], zoom=10)
view_state.bearing=15
view_state.pitch=70

# Render 
r = pdk.Deck(layers=[layer], 
             initial_view_state=view_state,
             tooltip=True
            ) 
r.to_html('merged_move_ingu.html')

import ipywidgets as widgets
from IPython.display import display
slider = widgets.IntSlider(6, min=0, max=23, step=1)

# Widget에서 사용할 함수 정의 
def on_change(v):
    results = merged_move_ingu[merged_move_ingu['hour'] == slider.value].to_dict(orient='records')
    layer.data = results
    r.update()

  # Deck과 슬라이더 연결
slider.observe(on_change, names='value')
display(slider)

IntSlider(value=6, max=23)

In [96]:
r.show()

DeckGLWidget(json_input='{"initialViewState": {"bearing": 15, "latitude": 37.565, "longitude": 126.986, "pitch…

In [99]:
# Make layer 
layer2 = pdk.Layer( 'PolygonLayer', # 사용할 Layer 타입
                  merged_move_ingu, # 시각화에 쓰일 데이터프레임
                  get_polygon='coordinates', # geometry 정보를 담고있는 컬럼 이름
                  get_fill_color='[0, 0, 200*남성비율]', # 각 데이터 별 rgb 또는 rgba 값 (0~255)
                  pickable=True, # 지도와 interactive 한 동작 on 
                  auto_highlight=True, # 마우스 오버(hover) 시 박스 출력 
                  getElevation='인구',
                  elevation_scale=0.1,
#                   elevation_range=[merged_move_ingu['인구'].min(), merged_move_ingu['인구'].max()],
                  extruded=True
                 ) 

# Set the viewport location 
center = [126.986, 37.565] 
view_state = pdk.ViewState( longitude=center[0], latitude=center[1], zoom=10)
view_state.bearing=15
view_state.pitch=70

# Render 
r2 = pdk.Deck(layers=[layer2], 
             initial_view_state=view_state,
             tooltip=True
            ) 
r2.to_html('merged_move_ingu_wrt_sex.html')

import ipywidgets as widgets
from IPython.display import display
slider2 = widgets.IntSlider(6, min=0, max=23, step=1)

# Widget에서 사용할 함수 정의 
def on_change(v):
    results = merged_move_ingu[merged_move_ingu['hour'] == slider.value].to_dict(orient='records')
    layer.data = results
    r.update()

  # Deck과 슬라이더 연결
slider2.observe(on_change, names='value')
display(slider2)

IntSlider(value=6, max=23)

In [100]:
r2.show()

DeckGLWidget(json_input='{"initialViewState": {"bearing": 15, "latitude": 37.565, "longitude": 126.986, "pitch…

## 각 동별 인구수 데이터가 필요 (동별, 시간대별, 성별)

## 두번째로는 동별, 연령대별 인구도

In [47]:
# Make layer 
layer = pdk.Layer( 'HexagonLayer', # 사용할 Layer 타입
                  merged_move_ingu, # 시각화에 쓰일 데이터프레임
                  get_polygon='coordinates', # geometry 정보를 담고있는 컬럼 이름
                  get_fill_color='[0, 255*정규화인구, 0]', # 각 데이터 별 rgb 또는 rgba 값 (0~255)
                  pickable=True, # 지도와 interactive 한 동작 on 
                  auto_highlight=True # 마우스 오버(hover) 시 박스 출력 
                 ) 

layer.extruded = True;
layer.get_elevation = '인구';
layer.elevation_scale = 1
# layer.elevation_range=[merged_move_ingu['인구'].min, merged_move_ingu['인구'].max]
# view_state.bearing=15
# view_state.pitch=45

# Set the viewport location 
center = [126.986, 37.565] 
view_state = pdk.ViewState( longitude=center[0], latitude=center[1], zoom=10)

# Render 
r = pdk.Deck(layers=[layer], initial_view_state=view_state) 
r.to_html('merged_move_ingu.html')

import ipywidgets as widgets
from IPython.display import display
slider = widgets.IntSlider(6, min=0, max=23, step=1)

# Widget에서 사용할 함수 정의 
def on_change(v):
    results = merged_move_ingu[merged_move_ingu['hour'] == slider.value].to_dict(orient='records')
    layer.data = results
    r.update()

  # Deck과 슬라이더 연결
slider.observe(on_change, names='value')
display(slider)
r.show()

IntSlider(value=6, max=23)

DeckGLWidget(json_input='{"initialViewState": {"latitude": 37.565, "longitude": 126.986, "zoom": 10}, "layers"…